services:
  WebhookPoC:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: webapi
    image: docker push pjaroszek/webhookpoc:latest
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: unless-stopped